<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Reo.Core.Database" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\EmailServer.Domain\EmailServer.Domain.csproj" />
    </ItemGroup>

</Project>
