// <auto-generated />
using System;
using EmailServer.Postgres.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EmailServer.Postgres.Migrations
{
    [DbContext(typeof(MeteringContext))]
    partial class MeteringContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EmailServer.Postgres.Models.MeteringEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ColdWater")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Electricity")
                        .HasColumnType("numeric");

                    b.Property<decimal>("HotWater")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SendingDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Meterings");
                });

            modelBuilder.Entity("EmailServer.Postgres.Models.ServiceCompanyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("PhoneNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ServiceCompanies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c0922377-d913-4533-b32c-8c9ef46a45bc"),
                            Email = "info@ooopek.com",
                            Name = "ООО Первая Эксплуатационная Компания",
                            PhoneNumber = 89281377770L,
                            ShortName = "ООО УК ПЭК"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
